### ISSUE TITLE
Configuration does not persist when installed to `$GOPATH/bin`

### ISSUE THREAD

**Issue by rowanjacobs** [mbellotti/netback#1]
When running `netback` from `$GOPATH/bin`, I get the following error on every command, even if I have already run `netback config`:
```
Configuration not found, please run `netback config` to set up
```

Furthermore, I also get the following error on commands other than `netback config` and `netback profile`:
```
2020/02/29 21:40:58 Please define characteristics of suspicious accounts by running the command `netback profile`
```

Based on [our Twitter conversation](https://twitter.com/bellmar/status/1234000014554419202) this may be because it can't save its configuration file. Maybe the configuration file could be saved to `~/.netback` or a similar static location?

**Comment by mbellotti** [comment]
> Based on our Twitter conversation this may be because it can't save its configuration file. Maybe the configuration file could be saved to ~/.netback or a similar static location?

Yup! It took me a little investigating to figure out how to do that in a cross compatible way (well fingers crossed anyway) but if you update to the latest version and rerun install it will save the config file to `~HOME/netback/config.yaml`

Nice side benefit, if you want to tweak the profile after its setup you can just edit that file directly rather than rerunning the wizard.

I will keep this issue open until you've had the opportunity to give it a try and confirm this works.

**Comment by rowanjacobs** [comment]
I successfully configured it! Thanks for the help.
